### PR TITLE
[fix] rviz crash after capture

### PR DESCRIPTION
**Pull request by juliangaal**
This PR introduces two changes

* fix opencv headers 
* Fix rviz crash in endless loop of service callback. Adapt switch case to skip capturing if a captured frame is currently captured
* `flag` can be accessed from multiple threads. Made threadsafe

### CODE REVIEW

**Comment by jclinton830** [comment]
@juliangaal which ROS version are you working with?

**Comment by juliangaal** [comment]
Noetic.

I realize that changing the OpenCV version isn't strictly necessary, but officially Ubuntu 18.04 doesn't have any support and OpenCV 4 is installed alongside noetic

**Comment by jclinton830** [comment]
> Noetic.
> 
> I realize that changing the OpenCV version isn't strictly necessary, but officially Ubuntu 18.04 doesn't have any support and OpenCV 4 is installed alongside noetic

Fair enough. If your changes are making it work successfully for Noetic maybe the best approach is to publish this as a different branch. We can call this branch Noetic.

**Comment by jclinton830** [comment]
@juliangaal I just made a new branch called noetic. Can you make a PR to merge your changes to this new branch?

**Comment by juliangaal** [comment]
Sure, I'll do that first thing Monday morning. We should ask the developer stuck with #37 to test the branch after the merge.

**Comment by jclinton830** [comment]
@juliangaal Yes that is the plan. I think it would be easier for her to test once these changes are available as a branch.

**Comment by juliangaal** [comment]
Had a couple minutes, the #38

**Pull request closed without merging**
